variables:
  - group: infrastructure

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/ltf-poc/identity

pool:
  vmImage: ubuntu-latest

  variables:
    - name: dir
      value: 'src'

steps:
- task: AzureKeyVault@2
  inputs:
    ConnectedServiceName: $(service_name)
    keyVaultName: $(key_vault_name)
    SecretsFilter: '*'
    RunAsPreJob: false

- bash: |
    echo "Subscription Id: $SUB"
  env:
    SUB: $(az-subscription)

- bash: |
    echo "buildConfig: $buildConfig"
  env:
    buildConfig: $(buildConfiguration)

- bash: ls -l
  displayName: 'list'
  
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

