variables:
  - group: infrastructure

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/ltf-poc/identity

pool:
  vmImage: ubuntu-latest

  variables:
    - name: dir
      value: 'src'

steps:
- task: AzureKeyVault@2
  inputs:
    ConnectedServiceName: $(service_name)
    keyVaultName: $(key_vault_name)
    SecretsFilter: '*'
    RunAsPreJob: false

# - task: CmdLine@2
#   inputs:
#     script: 'echo $(az-subscription) > secret.txt'

# - task: CopyFiles@2
#   inputs:
#     Contents: secret.txt
#     targetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'
    
- bash: ls -l
  displayName: 'list'

- bash: cd ltf-poc/src/identity
  displayName: 'change directory'

- bash: ls -l
  displayName: 'list'
  
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(az-subscription)
    appType: 'webAppLinux'
    appName: 'id-2694-destin-dev'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'