variables:
  - group: infrastructure

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/ltf-poc/api

pool:
  vmImage: ubuntu-latest

  variables:
    - name: dir
      value: 'src'

steps:
- task: AzureKeyVault@2
  inputs:
    ConnectedServiceName: $(service_name)
    keyVaultName: $(key_vault_name)
    SecretsFilter: '*'
    RunAsPreJob: false

- bash: ls -l
  displayName: 'list'

- script: dotnet build --configuration $(buildConfiguration) --runtime linux-x64
  workingDirectory: ltf-poc/src/identity
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'key_vault'
    appType: 'webAppLinux'
    appName: 'api-2694-destin-dev'
    package: '$(Build.ArtifactStagingDirectory)/**/api.zip'
